Algoritmo "semnome"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 03/04/2024
Var
// Seção de Declarações das variáveis 
num1, num2, num3, resultado : real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreval("Digite um número")
leia(num1)
limpatela
escreval("Digite um segundo número")
leia(num2)
limpatela
escreval("Digite um terceiro número")
leia(num3)
limpatela

resultado <- num1 + num2 + num3
escreval("A soma é:", resultado)
escreval("A subtração é:", num1 - num2 - num3)
escreval("A divisão é:", num1 / num2 / num3:1:3)
escreval("A multiplicação é:", num1 * num2 * num3)
escreval("A média é:", (num1 + num2 + num3) /3:1:3)

se(resultado >= 100) entao
    escreval("Passou de 100 a soma")
senao
    escreval("Nem chegou a 100 a soma")

fimse

escreval("EU SEI A TABUADA DO NÚMERO:")
leia (num1)
escreval(num1 * 1)
escreval(num1 * 2)
escreval(num1 * 3)
escreval(num1 * 4)
escreval(num1 * 5)
escreval(num1 * 6)
escreval(num1 * 7)
escreval(num1 * 8)
escreval(num1 * 9)
escreval(num1 * 10)
escreval(num1 * 11)
escreval(num1 * 12)
escreval(num1 * 13)
escreval(num1 * 14)
escreval(num1 * 15)
escreval(num1 * 16)
escreval(num1 * 17)
escreval(num1 * 18)
escreval(num1 * 19)
escreval(num1 * 20)

Fimalgoritmo