Algoritmo "semnome"
//
//
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 17/04/2024
Var
   // Seção de Declarações das variáveis
   i, n, l: inteiro

Inicio
   // Seção de Comandos, procedimento, funções, operadores, etc...
   escreval ("informe a tabuada desejada")
   leia (n)
   escreval ("informe o limite da tabuada")
   leia (l)
   para i de 1 ate l faca
      escreval (n, "x", i, "=", n*i)
   fimpara

   

Fimalgoritmo