Algoritmo "semnome"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 03/04/2024
Var
// Seção de Declarações das variáveis 
n1, n2, n3 = real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 

n3 <- n1
n1 <- n2
n2 <- n3

escreval(n2, " era o número A")

escreval(n1, " era o número B")


Fimalgoritmo